import Link from 'next/link';
import { ProductVisual } from './ProductVisual';
import { PlatformVisual } from './PlatformVisual';
import { SiteHeader } from './SiteHeader';
import { BrandMark } from './BrandMark';
import { packageConcepts, productPackages, siteConfig } from '../lib/site-config';

type Locale = 'ja' | 'en';
const text = {
 ja: { eyebrow:'Business Operations Platform', h1:'店舗運営を、ひとつの流れに。', lead:'シフト、勤怠、在庫、レシピ、日々の確認をひとつに。現場はスマホから、オーナーは管理画面から。', demo:'デモを見る', consult:'導入相談', problems:'毎日の「確認」を減らします。', transition:'ORUWAなら、確認が必要なことだけが見える。', flow:'一日の運営が、ひとつにつながる。', cafe:'小規模店舗の毎日の運営を一つに。', roles:'オーナーと現場、それぞれに必要な画面。', bilingual:'原文を守りながら、伝わる運営へ。', why:'小さく始めて、運営に合わせて育てられます。', trust:'開発経験に裏付けられたサポート。', pricing:'導入内容に応じてご案内します。', start:'運営の整理から、一緒に始めます。', faq:'よくあるご質問' },
 en: { eyebrow:'Business Operations Platform', h1:'Run your daily operations in one clear flow.', lead:'Bring schedules, attendance, inventory, recipes and daily follow-ups together. Your team works from mobile. Owners stay in control from one dashboard.', demo:'View demo', consult:'Book a consultation', problems:'Spend less time chasing daily updates.', transition:'ORUWA shows what actually needs your attention.', flow:'One clear flow through the working day.', cafe:'Bring small-store operations together.', roles:'The right view for owners and frontline staff.', bilingual:'Clearer operations, with the original always available.', why:'Start with Cafe and grow around your operations.', trust:'Supported by practical development experience.', pricing:'Pricing based on your implementation needs.', start:'We begin by understanding how you work.', faq:'Frequently asked questions' }
};
function Cta({locale}:{locale:Locale}) { const p=locale==='en'?'/en':''; return <section className="cta-section"><div className="shell cta-inner"><div><p className="eyebrow">ORUWA development</p><h2>{locale==='ja'?'ORUWAの製品と開発構想をご覧ください。':'Explore ORUWA products and development direction.'}</h2></div><div className="hero-actions"><Link className="button light" href={`${p}/products`}>{locale==='ja'?'製品を見る':'View products'}</Link><a className="button button-ghost" href={siteConfig.developerUrl} target="_blank" rel="noreferrer">IZUMI IT COMPANY ↗</a></div></div></section>; }
function Footer({locale}:{locale:Locale}) { const p=locale==='en'?'/en':''; return <footer className="footer"><div className="shell footer-grid release-footer-grid"><div><Link className="brand footer-brand" href={p||'/'}><BrandMark/><span>ORUWA</span></Link><p>Business Operations Platform<br/>{locale==='ja'?'日本の小規模事業者のために。':'Built for small businesses in Japan.'}</p></div><div><strong>{locale==='ja'?'公開中':'Published'}</strong><Link href={`${p}/products`}>{locale==='ja'?'製品・パッケージ':'Products & packages'}</Link><span>{locale==='ja'?'ORUWA Cafe 詳細は準備中':'ORUWA Cafe details are in preparation'}</span></div><div><strong>{locale==='ja'?'開発会社':'Developer'}</strong><a href={siteConfig.developerUrl} target="_blank" rel="noreferrer">IZUMI IT COMPANY ↗</a></div></div><div className="shell footer-bottom"><span>© 2026 ORUWA</span><span>{locale==='ja'?'本サイトは段階的に公開しています。':'This website is being published in stages.'}</span></div></footer>; }

function Packages({locale,showConcepts=false}:{locale:Locale,showConcepts?:boolean}) { const p=locale==='en'?'/en':''; return <section id="packages" className="section"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow">ORUWA Packages</p><h2>{locale==='ja'?'一つの基盤に、業種ごとのパッケージ。':'Industry packages on one shared platform.'}</h2><p>{showConcepts?(locale==='ja'?'ORUWA Cafeが第一パッケージです。共通の運営基盤に、業種ごとのパッケージを追加できる構造を目指しています。':'ORUWA Cafe is the first package. The platform is designed to support additional industry packages on one shared operational foundation.'):(locale==='ja'?'ORUWA Cafeは最初に完成したパッケージです。今後のパッケージも、同じ運営基盤に追加できるよう設計しています。':'ORUWA Cafe is the first completed package. Future packages can be added to the same operational foundation.')}</p></div><Link className="arrow-link" href={`${p}/products`}>{locale==='ja'?'製品一覧':'All products'} →</Link></div><div className={showConcepts?'package-grid top-package-grid':'package-grid'}>{productPackages.map(pkg=><article className={showConcepts?'package-card featured-package':'package-card'} key={pkg.slug}><div><span className="availability">{showConcepts?(locale==='ja'?'第一パッケージ':'First package'):(locale==='ja'?'提供中':'Available')}</span><p>{locale==='ja'?pkg.audienceJa:pkg.audienceEn}</p><h3>{pkg.name}</h3><p>{locale==='ja'?pkg.summaryJa:pkg.summaryEn}</p></div><span className="release-note">{locale==='ja'?'詳細ページは準備中':'Detailed page in preparation'}</span></article>)}{showConcepts&&packageConcepts.map(pkg=><article className="package-card concept-card" key={pkg.slug}><div><span className="concept-status">{locale==='ja'?'構想中':'Concept'}</span><p>{locale==='ja'?pkg.labelJa:pkg.labelEn}</p><h3>{pkg.name}</h3><p>{locale==='ja'?pkg.summaryJa:pkg.summaryEn}</p></div><span className="concept-note">{locale==='ja'?'提供内容・時期は未定':'Scope and timing not confirmed'}</span></article>)}</div></div></section>; }

function CustomExpansion({locale,compact=false}:{locale:Locale,compact?:boolean}) {
  const p=locale==='en'?'/en':'';
  const examples=locale==='ja'?
    [['Web','企業・店舗サイト'],['Map','地図・位置情報'],['Fleet','車両・移動管理'],['AI','AIエージェント'],['Link','外部サービス連携']]:
    [['Web','Company or store website'],['Map','Maps and location'],['Fleet','Vehicles and mobility'],['AI','AI agent'],['Link','External integrations']];
  return <section className={`custom-expansion ${compact?'custom-expansion-compact':'section'}`}><div className="shell custom-expansion-inner"><div className="custom-expansion-copy"><p className="eyebrow">Custom extensions</p><h2>{locale==='ja'?'標準パッケージに、必要な仕組みをプラス。':'Add what your operation uniquely needs.'}</h2><p>{locale==='ja'?'標準パッケージで共通業務を整えたうえで、会社独自の要件に合わせた機能やシステムも個別に設計・開発します。':'Start with a standard package, then add individually designed functionality for your company’s specific workflow.'}</p><div className="custom-price-note"><span>{locale==='ja'?'料金':'Pricing'}</span><strong>{locale==='ja'?'標準パッケージとは別にお見積り':'Quoted separately from the standard package'}</strong></div>{compact&&<Link className="arrow-link" href={`${p}/products#custom`}>{locale==='ja'?'個別対応について見る':'Explore custom extensions'} →</Link>}</div><div className="custom-example-grid">{examples.map(([mark,label])=><div key={mark}><span>{mark}</span><strong>{label}</strong></div>)}</div>{!compact&&<div className="custom-expansion-action"><p>{locale==='ja'?'ここにない内容でも、現在の運営と目的を確認して対応可否をご案内します。':'If your requirement is not listed, we will review your current operation and confirm what can be delivered.'}</p><a className="button" href={siteConfig.developerUrl} target="_blank" rel="noreferrer">{locale==='ja'?'開発会社を見る ↗':'Visit the developer ↗'}</a></div>}</div></section>;
}

function AccessModes({locale,compact=false}:{locale:Locale,compact?:boolean}) {
  const items=locale==='ja'?
    [['LINE','スタッフは、日常的に使うLINEから必要な業務画面へ。新しい操作の負担を抑えます。'],['Web','LINEを使わなくても、ブラウザから単独で利用できます。管理者の確認や設定にも対応します。']]:
    [['LINE','Staff can open the workflows they need from the LINE environment they already use every day.'],['Web','ORUWA also works independently in a browser, including management and configuration workflows.']];
  return <section className={`access-modes ${compact?'access-modes-compact':'section'}`}><div className="shell access-modes-inner"><div className="access-modes-heading"><p className="eyebrow">LINE + Web</p><h2>{locale==='ja'?'いつものLINEから。必要ならWebから。':'Work from LINE—or independently on the web.'}</h2><p>{locale==='ja'?'ORUWAはLINEだけに依存しません。役割や場面に合わせて、使いやすい入口を選べます。':'ORUWA is not dependent on LINE. Each role can use the access method that fits the situation.'}</p></div><div className="access-mode-cards">{items.map(([name,description],index)=><article className={index===0?'line-mode':'web-mode'} key={name}><div><span>{index===0?'L':'W'}</span><strong>{name}</strong></div><p>{description}</p></article>)}</div>{!compact&&<p className="access-truth-note">{locale==='ja'?'利用できるLINE連携の範囲は、パッケージと導入内容によって異なります。LINE公式アカウントなど外部サービスの費用は別途必要になる場合があります。':'Available LINE integration depends on the package and implementation scope. External service costs, including a LINE Official Account, may apply separately.'}</p>}</div></section>;
}

function Home({locale}:{locale:Locale}) { const t=text[locale], p=locale==='en'?'/en':''; return <>
  <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow">{t.eyebrow}</p><h1>{locale==='ja'?<>日々の運営を、<br/><span className="no-break">ひとつの流れに。</span></>:<>Run daily operations<br/><span className="no-break">in one clear flow.</span></>}</h1><p className="hero-lead">{locale==='ja'?'散らばる情報と毎日の確認を減らし、会社・店舗・現場・管理を一つの流れに。ORUWAは、日本の小規模事業者のための業務運営プラットフォームです。':'Reduce scattered information and repeated checks. ORUWA connects company, location, frontline work and management in one operational flow.'}</p><div className="hero-actions"><Link className="button" href={`${p}/products`}>{locale==='ja'?'製品を見る':'View products'}</Link><Link className="button button-secondary" href="#access">LINE + Web</Link></div><Link className="hero-package-link" href="#packages">{locale==='ja'?'すべてのパッケージを見る':'View all packages'} →</Link><ul className="trust-points"><li>{locale==='ja'?'第一パッケージ ORUWA Cafe':'First package: ORUWA Cafe'}</li><li>{locale==='ja'?'LINE・Web対応':'LINE and Web access'}</li><li>{locale==='ja'?'日本語・英語対応':'Japanese and English'}</li></ul></div><PlatformVisual locale={locale}/></div></section>
  <section className="sales-bridge"><div className="shell sales-bridge-inner"><div><span>{locale==='ja'?'最初のパッケージ':'The first package'}</span><h2>ORUWA Cafe</h2><p>{locale==='ja'?'シフト、勤怠、在庫、レシピ、日々の確認を一つに。現在、製品詳細ページと実際の画面を準備しています。':'Bring schedules, attendance, inventory, recipes and daily follow-ups together. The detailed product page and real product screens are now in preparation.'}</p></div><div className="sales-bridge-actions"><Link className="button" href={`${p}/products`}>{locale==='ja'?'製品一覧を見る':'View products'}</Link><Link className="arrow-link" href="#packages">{locale==='ja'?'構想中のパッケージ':'Package concepts'} →</Link></div></div></section>
  <div id="access"><AccessModes locale={locale} compact/></div>
  <section className="section"><div className="shell"><div className="section-heading"><p className="eyebrow">Operational friction</p><h2>{locale==='ja'?'業種が違っても、毎日の混乱には共通点があります。':'Different industries share the same operational friction.'}</h2></div><div className="problem-grid">{(locale==='ja'?['情報がメッセージや表に散らばる','現場の状況が管理側に届くのが遅い','担当者ごとに手順や確認方法が変わる','必要な判断に時間がかかる']:['Information is scattered across messages and sheets','Frontline updates reach management too late','Processes vary from person to person','Daily decisions take too much time']).map((x,i)=><article className="problem-card" key={x}><span>0{i+1}</span><h3>{x}</h3></article>)}</div><p className="section-transition">{locale==='ja'?'ORUWAは、業種ごとの運営を一つの流れに整えます。':'ORUWA turns industry-specific operations into one clear flow.'}</p></div></section>
  <section className="section section-tint"><div className="shell"><div className="section-heading"><p className="eyebrow">One operational flow</p><h2>{locale==='ja'?'現場の更新から、管理者の判断まで。':'From frontline updates to management decisions.'}</h2></div><div className="timeline platform-timeline">{(locale==='ja'?[['01 依頼','現場や顧客から情報を受ける'],['02 実行','担当者が必要な業務を進める'],['03 更新','状況・在庫・進捗を入力'],['04 確認','管理者が要確認だけを見る'],['05 改善','日々の運営を次に活かす']]:[['01 Request','Receive information from staff or customers'],['02 Work','The assigned person completes the task'],['03 Update','Record status, inventory or progress'],['04 Review','Managers see what needs attention'],['05 Improve','Use daily operations to inform the next step']]).map(([a,b])=><div className="timeline-item" key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></div></section>
  <Packages locale={locale} showConcepts/>
  <CustomExpansion locale={locale} compact/>
  <section className="section section-dark"><div className="shell"><div className="section-heading"><p className="eyebrow">One platform</p><h2>{locale==='ja'?'業種が変わっても、運営の基本はつながる。':'A shared operational foundation across industries.'}</h2><p>{locale==='ja'?'会社・店舗・役割に応じた管理、スマートフォンでの現場入力、日本語・英語の運用。ORUWAは共通基盤の上に、業種ごとのパッケージを追加できる構造です。':'Company, location and role management, mobile frontline input and bilingual operations form a shared foundation. Industry packages can be added without rebuilding the platform.'}</p></div><div className="platform-pillars">{(locale==='ja'?[['共通基盤','会社・店舗・役割に応じて整理'],['パッケージ構造','必要な業務から段階的に追加'],['現場と管理','スマホと管理画面を一つの流れに']]:[['Shared foundation','Organized by company, location and role'],['Package architecture','Add the operations each business needs'],['Frontline and management','Connect mobile work with owner oversight']]).map(([a,b])=><article key={a}><h3>{a}</h3><p>{b}</p></article>)}</div></div></section>
  <Trust locale={locale}/><Cta locale={locale}/>
  </>;
}

function Trust({locale}:{locale:Locale}) { return <section className="section trust-section"><div className="shell trust-grid"><div><p className="eyebrow">Developed in Japan</p><h2>{text[locale].trust}</h2><p>{locale==='ja'?'ORUWAは、Web制作・業務システム開発を行うIZUMI IT COMPANYが開発しています。':'ORUWA is developed by IZUMI IT COMPANY, with experience in web and operational system development in Japan.'}</p><a className="arrow-link" href={siteConfig.developerUrl} target="_blank" rel="noreferrer">IZUMI IT COMPANY ↗</a></div><div className="trust-numbers"><div><strong>2018</strong><span>{locale==='ja'?'設立':'Established'}</span></div><div><strong>400</strong><span>{locale==='ja'?'公式サイトに掲載された制作実績':'Projects stated on the corporate website'}</span></div></div></div><p className="shell disclaimer">{locale==='ja'?'これらはIZUMI IT COMPANYのWeb制作・開発領域での実績であり、ORUWAの導入社数を示すものではありません。':'These figures refer to IZUMI IT COMPANY’s web and development work. They do not represent the number of ORUWA customers.'}</p></section>; }
function Pricing({locale,compact=false}:{locale:Locale,compact?:boolean}) { const t=text[locale]; return <section className={`section ${compact?'section-tint':''}`}><div className="shell"><div className="section-heading"><p className="eyebrow">Pricing</p><h2>{t.pricing}</h2><p>{locale==='ja'?'店舗数、必要なモジュール、初期設定の内容を確認したうえでご案内します。':'We will propose the right setup after reviewing locations, modules and implementation needs.'}</p></div><div className="pricing-card"><div><span>ORUWA Cafe</span><strong>{siteConfig.pricingStatus==='inquiry'?(locale==='ja'?'お問い合わせ':'Contact us'):siteConfig.publicPrice}</strong></div><ul>{(locale==='ja'?['初期設定','追加店舗','追加モジュール','個別連携','LINE公式アカウント費用は別途']:['Initial setup','Additional locations','Additional modules','Custom integrations','LINE Official Account costs are separate']).map(x=><li key={x}>{x}</li>)}</ul><Link className="button" href={`${locale==='en'?'/en':''}/contact`}>{locale==='ja'?'相談する':'Discuss your needs'}</Link></div></div></section>; }

const detailCopy: Record<string,{eyebrow:string,title:string,lead:string,sections:Array<[string,string,string[]?]>}> = {
 cafe:{eyebrow:'ORUWA Cafe',title:'毎日の運営を、確認しやすく、伝わりやすく。',lead:'小規模なカフェや飲食店のシフト、勤怠、在庫、レシピを、ManagerとStaffそれぞれに分かりやすい流れへ。',sections:[['Manager Today','いま対応すべきことを、散らばったメッセージから探す必要を減らします。',['不足在庫','勤務修正','シフト交代']],['Inventory','スタッフが現場から入力し、Managerが不足や確認事項を把握します。',['スマホ入力','不足表示','日々の確認']],['Recipes','最新版のレシピと手順を、必要な人がスマホから確認できます。',['日本語原文','英語翻訳','役割別アクセス']],['Schedule & Attendance','勤務予定、出退勤、修正依頼、交代申請を一つの運営フローへ。',['予定確認','修正依頼','Manager承認']]]},
 'en/cafe':{eyebrow:'ORUWA Cafe',title:'Daily operations that are easier to see and easier to share.',lead:'Bring schedules, attendance, inventory and recipes into clear Manager and Staff workflows for small cafés and restaurants.',sections:[['Manager Today','Reduce time spent searching through scattered messages for operational follow-ups.',['Shortages','Attendance corrections','Shift exchanges']],['Inventory','Staff update counts from mobile; managers see shortages and follow-ups.',['Mobile input','Shortage status','Daily checks']],['Recipes','Keep current recipes and instructions available to the right people.',['Japanese source','English translation','Role-based access']],['Schedule & Attendance','Connect plans, attendance, corrections and shift requests.',['Schedule view','Correction requests','Manager approval']]]},
 security:{eyebrow:'Security',title:'運営データを、会社・店舗・役割に応じて管理。',lead:'ORUWAは、会社ごとにデータを分離し、役割に応じたアクセス権限を管理する考え方で設計しています。',sections:[['データの分離','会社や店舗の境界を保ち、必要な業務データだけにアクセスできる設計を採用します。'],['役割に応じたアクセス','ManagerとStaffでは、閲覧・操作できる範囲を分けます。'],['開発と運用','秘密情報を公開画面に置かず、変更を確認してから反映する運用を重視します。'],['プライバシー','必要以上の情報を収集せず、利用目的と保存方法を明確にします。']]},
 'en/security':{eyebrow:'Security',title:'Operational data managed by company, location and role.',lead:'ORUWA is designed around data separation between companies and access controls appropriate to each role.',sections:[['Data separation','Company and location boundaries help keep operational data in the appropriate scope.'],['Role-based access','Managers and staff receive different viewing and action permissions.'],['Development and operations','Secrets stay out of public pages, and changes are reviewed before release.'],['Privacy','We aim to collect only necessary information and clarify its purpose and handling.']]},
 about:{eyebrow:'About ORUWA',title:'日本の小規模事業者の運営を、もっと分かりやすく。',lead:'ORUWAは、日々の業務が人とツールの間で分断される問題を、ひとつの運営フローに整えるプラットフォームです。',sections:[['私たちの考え','新しいツールを増やすことではなく、毎日の確認と伝達を減らすことから考えます。'],['最初の製品','ORUWA Cafeから始め、現場で必要な運営の基盤を段階的に広げます。'],['開発会社','IZUMI IT COMPANYが日本国内で開発・導入支援を行います。']]},
 'en/about':{eyebrow:'About ORUWA',title:'Clearer operations for small businesses in Japan.',lead:'ORUWA brings daily work that is scattered across people and tools into one operational flow.',sections:[['Our approach','We begin with reducing daily checks and communication gaps, not adding more tools.'],['Our first product','ORUWA Cafe is the first package, with a modular foundation for future operational needs.'],['Developer','ORUWA is developed and supported in Japan by IZUMI IT COMPANY.']]}
};
function Detail({locale,keyName}:{locale:Locale,keyName:string}) { const d=detailCopy[keyName]; return <><section className="page-hero"><div className="shell narrow"><p className="eyebrow">{d.eyebrow}</p><h1>{d.title}</h1><p>{d.lead}</p></div></section>{keyName.endsWith('cafe')&&<section id="demo" className="section"><div className="shell demo-grid"><div><p className="eyebrow">Product demo</p><h2>{locale==='ja'?'ManagerとStaff、二つの視点。':'Two focused views: Manager and Staff.'}</h2><p>{locale==='ja'?'以下は製品UIをもとにしたデモ用構成です。実在する顧客データは使用していません。':'This demo composition is based on the product UI and uses no real customer data.'}</p></div><ProductVisual compact/></div></section>}<section className="section section-tint"><div className="shell detail-grid">{d.sections.map(([a,b,c])=><article className="detail-card" key={a}><p className="eyebrow">{a}</p><h2>{a}</h2><p>{b}</p>{c&&<ul>{c.map(x=><li key={x}>{x}</li>)}</ul>}</article>)}</div></section>{keyName.endsWith('cafe')&&<><section className="section"><div className="shell"><div className="section-heading"><p className="eyebrow">Implementation</p><h2>{locale==='ja'?'標準化された導入フローを準備しています。':'A structured implementation flow.'}</h2></div><ol className="steps">{(locale==='ja'?['導入相談','現在の運用確認','デモ確認','初期設定','スタッフ案内','利用開始']:['Consultation','Current workflow review','Demo review','Initial setup','Staff guidance','Start using ORUWA']).map((x,i)=><li key={x}><span>{i+1}</span>{x}</li>)}</ol></div></section><Faq locale={locale}/></>}<Cta locale={locale}/></>; }
function Faq({locale}:{locale:Locale}) { const qs=locale==='ja'?[['小規模な店舗でも使えますか？','はい。小規模店舗の毎日の運営を整理することから設計しています。'],['LINE公式アカウントは必要ですか？','利用するパッケージと連携範囲によって異なります。ORUWAはWebアプリとして単独でも利用でき、すべての機能がLINEを必須とするわけではありません。'],['スマートフォンで使えますか？','Staff向けの主要な操作はスマートフォンで使いやすい設計です。'],['英語に対応していますか？','日本語・英語の画面とコンテンツ運用を用意しています。機械翻訳では原文も確認できます。'],['導入にはどのくらいかかりますか？','現在の運用と必要な初期設定を確認してご案内します。']]:[['Is it suitable for a small store?','Yes. ORUWA Cafe is designed around the daily needs of small operations.'],['Do we need a LINE Official Account?','It depends on the package and integration scope. ORUWA also works as an independent web app, and not every feature requires LINE.'],['Can staff use it on mobile?','Core Staff workflows are designed for mobile use.'],['Does it support English?','Japanese and English interfaces and content workflows are included. The source remains available with machine translation.'],['How long does implementation take?','We review your current workflow and setup needs before providing a schedule.']]; return <section className="section"><div className="shell narrow"><div className="section-heading"><p className="eyebrow">FAQ</p><h2>{text[locale].faq}</h2></div><div className="faq-list">{qs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>; }

function Products({locale}:{locale:Locale}) {
  const cafe=productPackages[0];
  const modules=locale==='ja'?['シフト','勤怠','在庫','レシピ']:['Schedules','Attendance','Inventory','Recipes'];
  const foundation=locale==='ja'?
    [['会社・拠点','会社、店舗、現場を同じ構造で整理。'],['権限と役割','管理者と現場に、必要な情報だけを表示。'],['モバイル運用','現場の入力と確認を、スマートフォンから。'],['日本語・英語','働く人に合わせて、二つの言語で運用。']]:
    [['Company & locations','Organize companies, stores and worksites in one structure.'],['Roles & access','Show owners and frontline teams only what they need.'],['Mobile workflows','Capture and confirm frontline work from mobile.'],['Japanese & English','Support operations in both working languages.']];
  return <>
    <section className="products-hero"><div className="shell products-hero-grid"><div><p className="eyebrow">ORUWA Packages</p><h1>{locale==='ja'?<>一つの運営基盤に、<br/>業種ごとのパッケージ。</>:<>One operational foundation.<br/>Packages for each industry.</>}</h1><p>{locale==='ja'?'共通する管理はORUWAにまとめ、業種ならではの仕事は専用パッケージでつなぐ。Cafeから始まり、必要な領域へ広げていきます。':'ORUWA brings shared management into one foundation, then connects industry-specific work through focused packages—starting with Cafe.'}</p></div><div className="products-hero-summary"><span>{locale==='ja'?'現在':'Now'}</span><strong>1</strong><p>{locale==='ja'?'最初のパッケージを公開':'first package available to explore'}</p><div></div><span>{locale==='ja'?'次へ':'Next'}</span><strong>4</strong><p>{locale==='ja'?'業種パッケージを構想中':'industry package concepts'}</p></div></div></section>

    <section className="section product-catalog"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow">First package</p><h2>{locale==='ja'?'まず、Cafeの運営から。':'Starting with café operations.'}</h2><p>{locale==='ja'?'最初のパッケージとして開発を進めています。詳細ページと実際の製品画面は準備中です。':'Development is progressing as ORUWA’s first package. Its detailed page and real product screens are in preparation.'}</p></div><span className="catalog-legend available-legend">{locale==='ja'?'開発中':'In development'}</span></div><article className="cafe-product-card"><div className="cafe-product-copy"><span className="availability">{locale==='ja'?'第一パッケージ':'First package'}</span><p className="product-audience">{locale==='ja'?cafe.audienceJa:cafe.audienceEn}</p><h3>{cafe.name}</h3><p>{locale==='ja'?cafe.summaryJa:cafe.summaryEn}</p><ul className="product-module-list">{modules.map((module,index)=><li key={module}><span>{String(index+1).padStart(2,'0')}</span>{module}</li>)}</ul><p className="release-note prominent-release-note">{locale==='ja'?'製品詳細・デモ画面は準備中です':'Product details and demo screens are in preparation'}</p></div><div className="cafe-product-flow" aria-label={locale==='ja'?'Cafeパッケージの運営フロー':'Cafe package workflow'}><div className="flow-core"><small>ORUWA</small><strong>Cafe</strong></div>{modules.map((module,index)=><div className="flow-step" key={module}><span>{String(index+1).padStart(2,'0')}</span><strong>{module}</strong><small>{locale==='ja'?['計画する','記録する','確認する','共有する'][index]:['Plan','Record','Review','Share'][index]}</small></div>)}</div></article></div></section>

    <section className="section concept-catalog section-tint"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow">Package concepts</p><h2>{locale==='ja'?'次の業種へ、同じ考え方を。':'The same approach for more industries.'}</h2><p>{locale==='ja'?'以下は検討中の方向性です。提供内容や時期はまだ確定していません。':'These are directions under consideration. Their scope and timing are not yet confirmed.'}</p></div><span className="catalog-legend concept-legend">{locale==='ja'?'構想中':'Concepts'}</span></div><div className="concept-catalog-grid">{packageConcepts.map((pkg,index)=><article className="concept-product-card" key={pkg.slug}><div className="concept-card-top"><span>0{index+1}</span><span className="concept-status">{locale==='ja'?'構想中':'Concept'}</span></div><p>{locale==='ja'?pkg.labelJa:pkg.labelEn}</p><h3>{pkg.name}</h3><p>{locale==='ja'?pkg.summaryJa:pkg.summaryEn}</p><div className="concept-divider"></div><small>{locale==='ja'?'提供内容・時期は未定':'Scope and timing not confirmed'}</small></article>)}</div></div></section>

    <AccessModes locale={locale}/>
    <div id="custom"><CustomExpansion locale={locale}/></div>

    <section className="section products-foundation"><div className="shell"><div className="foundation-intro"><p className="eyebrow">One shared foundation</p><h2>{locale==='ja'?'パッケージが増えても、運営はばらばらにしない。':'More packages, without more fragmentation.'}</h2><p>{locale==='ja'?'新しい業務を別の仕組みに分けるのではなく、共通する会社・拠点・役割の上に追加します。':'New workflows build on the same company, location and role structure instead of becoming another disconnected system.'}</p></div><div className="foundation-path" aria-label={locale==='ja'?'パッケージ追加の仕組み':'How packages extend ORUWA'}><div><span>01</span><strong>{locale==='ja'?'ORUWA共通基盤':'ORUWA foundation'}</strong><small>{locale==='ja'?'会社・拠点・役割':'Company, locations, roles'}</small></div><i>+</i><div><span>02</span><strong>{locale==='ja'?'業種パッケージ':'Industry package'}</strong><small>{locale==='ja'?'業種固有の業務':'Industry-specific work'}</small></div><i>=</i><div className="path-result"><span>03</span><strong>{locale==='ja'?'一つの運営フロー':'One operational flow'}</strong><small>{locale==='ja'?'管理と現場がつながる':'Management and frontline connected'}</small></div></div><div className="foundation-grid">{foundation.map(([a,b],index)=><article key={a}><span>0{index+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></div></section>
    <Cta locale={locale}/>
  </>;
}

function Contact({locale}:{locale:Locale}) { return <><section className="page-hero"><div className="shell narrow"><p className="eyebrow">Contact</p><h1>{locale==='ja'?'まずは、現在の運営をお聞かせください。':'Tell us how your operations work today.'}</h1><p>{locale==='ja'?'送信機能は現在準備中です。入力内容はこのページから送信・保存されません。':'Form submission is being prepared. Information entered here is not currently sent or stored.'}</p></div></section><section className="section"><div className="shell contact-grid"><form className="contact-form" aria-describedby="form-status"><div className="form-grid">{(locale==='ja'?[['店舗・会社名','text'],['お名前','text'],['メールアドレス','email'],['業種','text'],['店舗数','number'],['スタッフ数の目安','number']]:[['Company / store name','text'],['Contact name','text'],['Email','email'],['Business type','text'],['Number of locations','number'],['Approximate staff count','number']]).map(([label,type])=><label key={label}>{label}<input type={type} disabled/></label>)}</div><label>{locale==='ja'?'現在の運営課題':'Current operational challenge'}<textarea disabled rows={5}/></label><label>{locale==='ja'?'希望する連絡方法':'Preferred contact method'}<select disabled><option>{locale==='ja'?'選択してください':'Select'}</option></select></label><label className="consent"><input type="checkbox" disabled/>{locale==='ja'?'プライバシーポリシーを確認しました':'I have reviewed the privacy policy'}</label><button className="button" disabled type="button">{locale==='ja'?'送信機能は準備中です':'Submission coming soon'}</button><p id="form-status" className="truth-note">{locale==='ja'?'有効化には、送信先・保存方針・スパム対策の確認が必要です。':'Activation requires a confirmed provider, storage policy and anti-spam controls.'}</p></form><aside className="contact-aside"><h2>{locale==='ja'?'相談で確認すること':'What we cover'}</h2><ul>{(locale==='ja'?['現在使っているツール','確認に時間がかかる業務','店舗数とスタッフ構成','必要なデモ範囲']:['Your current tools','Tasks that require repeated checks','Locations and staff structure','The demo scope you need']).map(x=><li key={x}>{x}</li>)}</ul></aside></div></section></>; }
function Login({locale}:{locale:Locale}) { return <section className="login-page"><div className="login-card"><Link className="brand" href={locale==='en'?'/en':'/'}><BrandMark/><span>ORUWA</span></Link><p className="eyebrow">Customer portal</p><h1>{locale==='ja'?'ログイン機能は準備中です。':'Customer login is coming soon.'}</h1><p>{locale==='ja'?'このマーケティングサイトでは、仮のログインフォームを提供していません。将来のCustomer Portalは、安全な別サービスとして提供します。':'This marketing site does not provide a placeholder login form. The future Customer Portal will be delivered as a separate secure service.'}</p><div className="hero-actions"><Link className="button" href={`${locale==='en'?'/en':''}/contact`}>{locale==='ja'?'導入相談':'Book a consultation'}</Link><Link className="button button-secondary" href={`${locale==='en'?'/en':''}/cafe#demo`}>{locale==='ja'?'デモを見る':'View demo'}</Link></div></div></section>; }
function Legal({kind}:{kind:string}) { const titles:{[k:string]:string}={privacy:'プライバシーポリシー',terms:'利用規約', 'commercial-disclosure':'特定商取引法に基づく表記'}; return <section className="page-hero legal"><div className="shell narrow"><p className="eyebrow">Legal template</p><h1>{titles[kind]}</h1><div className="legal-notice"><strong>公開前の確認が必要です</strong><p>このページは構造テンプレートです。事業者名、住所、連絡先、責任者、提供条件、個人情報の取扱いなどは、所有者および必要に応じて専門家による確認後に掲載します。</p></div>{['事業者情報','適用範囲','収集・利用する情報','利用目的','第三者提供・外部サービス','保存期間と安全管理','お問い合わせ窓口','改定'].map(x=><section className="legal-section" key={x}><h2>{x}</h2><p>［所有者確認後に記載］</p></section>)}</div></section>; }

export function SitePage({path}:{path:string}) { const locale:Locale=path==='/en'||path.startsWith('/en/')?'en':'ja'; const keyName=path.replace(/^\//,'')||'home'; let content:React.ReactNode;
  if(keyName==='home'||keyName==='en') content=<Home locale={locale}/>;
  else if(keyName==='pricing'||keyName==='en/pricing') content=<><section className="page-hero"><div className="shell narrow"><p className="eyebrow">Pricing</p><h1>{text[locale].pricing}</h1><p>{locale==='ja'?'価格は一か所の設定で管理し、確定前は具体的な金額を表示しません。':'Pricing is managed centrally; no unconfirmed amount is displayed.'}</p></div></section><Pricing locale={locale}/><Cta locale={locale}/></>;
  else if(keyName==='contact'||keyName==='en/contact') content=<Contact locale={locale}/>;
  else if(keyName==='products'||keyName==='en/products') content=<Products locale={locale}/>;
  else if(keyName==='login'||keyName==='en/login') content=<Login locale={locale}/>;
  else if(['privacy','terms','commercial-disclosure'].includes(keyName)) content=<Legal kind={keyName}/>;
  else if(detailCopy[keyName]) content=<Detail locale={locale} keyName={keyName}/>;
  else content=<Home locale={locale}/>;
  const hideShell=keyName==='login'||keyName==='en/login'; return <>{!hideShell&&<SiteHeader locale={locale} path={path}/>}<main>{content}</main>{!hideShell&&<Footer locale={locale}/>}</>;
}
